### PR TITLE
Fix a namespace issue caused by

### PR DESCRIPTION
**Pull request by alnutile**
This submission

https://github.com/iron-io/iron_core_php/commit/538e1ef55863a63f606b3699877cb0394acc2c97

### CODE REVIEW

**Comment by thousandsofthem** [comment]
@alnutile at this moment IronWorker library is using older `0.*` version of IronCore, no fix required.
After upcoming update, it'll be rewritten to use namespaces for itself && IronCore

**Comment by alnutile** [comment]
Any thoughts on how this library should set its composer
https://github.com/iron-io/laraworker
Right now it is broke without my fork?


On Monday, March 30, 2015, Alexander Shapiotko <notifications@github.com>
wrote:

> @alnutile <https://github.com/alnutile> at this moment IronWorker library
> is using older 0.* version of IronCore, no fix required.
> After upcoming update, it'll be rewritten to use namespaces for itself &&
> IronCore
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iron-io/iron_worker_php/pull/27#issuecomment-87762547>
> .
>


-- 
Al Nutile
http://alfrednutile.info/about
413.345.5103

**Comment by thousandsofthem** [comment]
providing 
```
"iron-io/iron_mq": "1.*",
"iron-io/iron_worker": "1.*"
```
is enough to get it working, both 1x MQ and Worker branch are using same 0x IronCore library

**Comment by alnutile** [comment]
Okay since it is already set to that https://github.com/iron-io/laraworker/blob/master/composer.json I will try a fresh install and see if the issues comes up again.

**Pull request closed without merging**
