### PR TITLE
Add label parameter for postScheduleAdvanced method

### PR DESCRIPTION
**Pull request by alex-litvak**

### CODE REVIEW

**Comment by sunloverz** [comment]
@alex-litvak could you please add cluster and update readme

**Comment by sunloverz** [comment]
@rkononov let's merge

**Comment by nodesocket** [comment]
No version bump? Should be 1.4.4 right?

**Comment by thousandsofthem** [comment]
Already there.check it

**Comment by nodesocket** [comment]
Don't see it?

https://github.com/iron-io/iron_worker_php/blob/master/IronWorker.class.php#L9

and

https://github.com/iron-io/iron_worker_php/blob/master/IronWorker.class.php#L27

**Comment by thousandsofthem** [comment]
Ouch. Sorry, my bad. tagged the repo but didn't update these lines. should be ok now

**Pull request merged**
